### ISSUE TITLE
Node version update from 16.* to 18.*

### ISSUE THREAD

**Issue by gichinna-fadv** [Azure/data-factory-export-action#6]
Node version update from 16.* to 18.*

**Comment by fedeoliv** [comment]
@gichinna-fadv this issue was fixed on #8 and available on v1.2.1. Additionally, please check out the [archival notice](https://github.com/Azure/data-factory-export-action?tab=readme-ov-file#%EF%B8%8F-important-notice) as it will no longer be maintained. Thank you for your support and understanding!
